twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
   
    #enregistrement du theme de formulaire pour bulma
    form_theme: ['includes/_form_theme_bulma.html.twig']